service: creditalks
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: sa-east-1
functions:
  api:
    handler: index.handler
    role: ${ssm:${self:custom.stage}-${self:service}-users-iam-role}
    environment:
     DYNAMODB_USERS_TABLE: ${ssm:${self:custom.stage}-${self:service}-dynamodb-users-table}
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
custom:
  stage: ${opt:stage, self:provider.stage}
